name: Latest blog post workflow
on:
  repository_dispatch:
    types: [new-post]
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for 5 minutes
        run: sleep 5m
      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.encryptopia.dev/feed.xml"
